# cat Dockerfile 
FROM nginx:stable-alpine

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./00-http.conf ./default.conf /etc/nginx/conf.d/
COPY ./00-http.conf ./default.conf /var/www/conf.d/

RUN mkdir -p /var/www/html /tmp/nginx && \
  rm -rf /var/cache/nginx && ln -s /tmp/nginx /var/cache/nginx && \
  chmod 777 /var/www /var/www/* /tmp/nginx 

USER nginx

EXPOSE 10080 10443

CMD ["nginx"]